name: Android Release Metadata
on:
  workflow_dispatch: # Manual trigger

jobs:
  android-release-metadata:
    name: Upload Google Play metadata
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Parallel submodules checkout
        shell: bash
        run: git submodule update --depth 1 --init --recursive --jobs=$(($(nproc) * 20))

      - name: Checkout screenshots
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.SCREENSHOTS_REPO }}
          ssh-key: ${{ secrets.SCREENSHOTS_SSH_KEY }}
          ref: master
          path: screenshots

      # This symlink is not stored in the repo because Linter checks fail for the FDroid build.
      # Linter complains about an invalid symlink (we don't check out screenshots for FDroid).
      - name: Create symlink for GP screenshots
        shell: bash
        run: |
          for locale in en-US tr-TR; do
             ln -sf ../../../../../../screenshots/android/${locale}/graphics android/src/google/play/listings/${locale}/graphics
          done

      - name: Checkout private keys
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.PRIVATE_REPO }}
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
          ref: master
          path: private.git

      - name: Configure repo with private keys
        shell: bash
        run: |
          ./configure.sh ./private.git
          rm -rf ./private.git

      - name: Upload
        shell: bash
        run: ./gradlew publishGoogleReleaseListing
        working-directory: android
        timeout-minutes: 5
